name: rider_app
description: Puyo Delivery - App del Rider
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  flutter_background_service: ^5.0.0
  flutter_local_notifications: ^17.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.0
  permission_handler: ^11.1.0
  vibration: ^3.1.6
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
